name: flashlight-develop-a-module
services:
  prestashop:
    image: prestashop/prestashop-flashlight:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PS_DOMAIN=157.180.30.141
      - INIT_SCRIPTS_DIR=/tmp/init-scripts
    ports:
      - 80:80
    volumes:
      - ./init-scripts:/tmp/init-scripts:ro
      - type: bind
        source: ./modules/activeproductexportxml
        target: /var/www/html/modules/activeproductexportxml

  mysql:
    image: mariadb:lts
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop